apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.global.postgresql.existingSecret }}
type: Opaque
data:
  postgresql-postgres-password: {{ default "" .Values.postgres_configs.POSTGRES_PASSWORD | b64enc | quote }}