apiVersion: v1
kind: Secret
metadata:
  name: {{- include "database.fullname"}}-auth
type: Opaque
data:
  username: {{ .Values.POSTGRES_USER | b64enc | quote }}
  password: {{ .Values.POSTGRES_PASSWORD | b64enc | quote }}