apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-user-pass-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres_configs.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres_configs.POSTGRES_PASSWORD | b64enc | quote }}